---
driver:
  name: vagrant
  provider: vmware_fusion
  # http_proxy: http://www-proxy.us.oracle.com:80
  # https_proxy: http://www-proxy.us.oracle.com:80
  # provision_command: "env http_proxy=http://www-proxy.us.oracle.com:80 bash -c 'curl -L http://www.getchef.com/chef/install.sh | bash'"
  # vagrantfiles:
  #   - Vagrantfile.rb

provisioner:
  name: chef_solo
  # chef_omnibus_url: http://www.getchef.com/chef/install.sh

platforms:
  - name: debian-7.2.0
    driver_config:
      ssh_timeout: 45
      ssh_retries: 10
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: oel-7.0
    driver_config:
      box: OEL-7.2-x86_64
      ssh_timeout: 45
      ssh_retries: 10
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: oel-6.6
    driver_config:
      box: OEL-6.6
      ssh_timeout: 45
      ssh_retries: 10
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: oel-5.8
    driver_config:
      box: OEL-5.8
      ssh_timeout: 45
      ssh_retries: 10
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: windows-2012r2
    transport:
      name: winrm
    driver_config:
      box: win2012r2
      ssh_timeout: 45
      ssh_retries: 10
      customize:
        memory: 4096
        cpus: 2
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: windows-8.1
    transport:
      name: winrm
    driver_config:
      box: win81x64
      ssh_timeout: 45
      ssh_retries: 10
      customize:
        memory: 4096
        cpus: 2
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: solaris-10
    driver_config:
      box: solaris10-x86_64
      ssh_timeout: 45
      ssh_retries: 10
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]
  - name: solaris-11.2
    driver_config:
      box: solaris11_2-x86_64
      ssh_timeout: 45
      ssh_retries: 10
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["/Users/edwinbiemond/software", "/software"]

suites:
  - name: wls1221
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
      - recipe[fmw_inst::soa_suite]
      - recipe[fmw_inst::service_bus]
    attributes:
      fmw:
        java_home_dir:           "/usr/java/jdk1.8.0_111"
        middleware_home_dir:     "/opt/oracle/middleware_1221"
        version:                 "12.2.1.2"
      fmw_jdk:
        source_file:             "/software/jdk-8u111-linux-x64.tar.gz"
      fmw_wls:
        source_file:             "/software/fmw_12.2.1.2.0_infrastructure.jar"
        install_type:            "infra"
      fmw_inst:
        soa_suite_source_file:   "/software/fmw_12.2.1.2.0_soa_Disk1_1of1.zip"
        soa_suite_install_type:  "BPM"
        service_bus_source_file: "/software/fmw_12.2.1.2.0_osb_Disk1_1of1.zip"
    excludes:
      - windows-2012r2
      - windows-8.1
      - solaris-11.2
      - solaris-10

  - name: wls1213
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
      - recipe[fmw_inst::soa_suite]
      - recipe[fmw_inst::service_bus]
      - recipe[fmw_inst::mft]
    attributes:
      fmw:
        java_home_dir:           "/usr/java/jdk1.7.0_75"
        middleware_home_dir:     "/opt/oracle/middleware_1213"
        version:                 "12.1.3"
      fmw_jdk:
        source_file:             "/software/jdk-7u75-linux-x64.tar.gz"
      fmw_wls:
        source_file:             "/software/fmw_12.1.3.0.0_infrastructure.jar"
        install_type:            "infra"
      fmw_inst:
        soa_suite_source_file:   "/software/fmw_12.1.3.0.0_soa_Disk1_1of1.zip"
        soa_suite_install_type:  "BPM"
        service_bus_source_file: "/software/fmw_12.1.3.0.0_osb_Disk1_1of1.zip"
        mft_source_file:         "/software/fmw_12.1.3.0.0_mft_Disk1_1of1.zip"
    excludes:
      - windows-2012r2
      - windows-8.1
      - solaris-11.2
      - solaris-10

  - name: wls1213_sol
    run_list:
      - recipe[artifact-deployer]
      - recipe[fmw_jdk::install]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
      - recipe[fmw_inst::soa_suite]
      - recipe[fmw_inst::service_bus]
      - recipe[fmw_inst::mft]
    attributes:
      fmw:
        java_home_dir:           "/usr/jdk/instances/jdk1.7.0_75"
        middleware_home_dir:     "/opt/oracle/middleware_1213"
        version:                 "12.1.3"
      fmw_jdk:
        source_file:             "/software/jdk-7u75-solaris-i586.tar.gz"
        source_x64_file:         "/software/jdk-7u75-solaris-x64.tar.gz"
      fmw_wls:
        source_file:             "/software/fmw_12.1.3.0.0_infrastructure.jar"
        install_type:            "infra"
      fmw_inst:
        soa_suite_source_file:   "/software/fmw_12.1.3.0.0_soa_Disk1_1of1.zip"
        soa_suite_install_type:  "BPM"
        service_bus_source_file: "/software/fmw_12.1.3.0.0_osb_Disk1_1of1.zip"
        mft_source_file:         "/software/fmw_12.1.3.0.0_mft_Disk1_1of1.zip"
    excludes:
      - windows-2012r2
      - windows-8.1
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8

  - name: wls1213_win
    run_list:
      - recipe[artifact-deployer]
      - recipe[fmw_jdk::install]
      - recipe[fmw_wls::install]
      - recipe[fmw_inst::soa_suite]
      - recipe[fmw_inst::service_bus]
      - recipe[fmw_inst::mft]
      - recipe[fmw_inst::oim]
    attributes:
      fmw:
        java_home_dir:           "c:\\java\\jdk1.7.0_75"
        middleware_home_dir:     "c:\\oracle\\middleware_1213"
        version:                 "12.1.3"
        tmp_dir:                 "C:\\Users\\vagrant\\AppData\\Local\\temp"
      fmw_jdk:
        source_file:             "c:\\software\\jdk-7u75-windows-x64.exe"
      fmw_wls:
        source_file:             "c:\\software\\fmw_12.1.3.0.0_infrastructure.jar"
        install_type:            "infra"
      fmw_inst:
        soa_suite_source_file:   "c:\\software\\fmw_12.1.3.0.0_soa_Disk1_1of1.zip"
        soa_suite_install_type:  "BPM"
        service_bus_source_file: "c:\\software\\fmw_12.1.3.0.0_osb_Disk1_1of1.zip"
        mft_source_file:         "c:\\software\\fmw_12.1.3.0.0_mft_Disk1_1of1.zip"
    excludes:
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8
      - solaris-11.2
      - solaris-10

  - name: wls1036
    run_list:
      - recipe[artifact-deployer]
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
      - recipe[fmw_inst::webcenter]
      - recipe[fmw_inst::soa_suite]
      - recipe[fmw_inst::service_bus]
    attributes:
      fmw:
        java_home_dir:           "/usr/java/jdk1.7.0_75"
        middleware_home_dir:     "/opt/oracle/middleware_1036"
        version:                 "10.3.6"
      fmw_jdk:
        source_file:             "/software/jdk-7u75-linux-x64.tar.gz"
      fmw_wls:
        source_file:             "/software/wls1036_generic.jar"
      fmw_inst:
        soa_suite_source_file:   "/software/ofm_soa_generic_11.1.1.7.0_disk1_1of2.zip"
        soa_suite_source_2_file: "/software/ofm_soa_generic_11.1.1.7.0_disk1_2of2.zip"
        service_bus_source_file: "/software/ofm_osb_generic_11.1.1.7.0_disk1_1of1.zip"
        webcenter_source_file:   "/software/ofm_wc_generic_11.1.1.9.0_disk1_1of2.zip"
        webcenter_source_2_file: "/software/ofm_wc_generic_11.1.1.9.0_disk1_2of2.zip"
    excludes:
      - windows-2012r2
      - windows-8.1
      - solaris-11.2
      - solaris-10

  - name: wls1036_sol
    run_list:
      - recipe[artifact-deployer]
      - recipe[fmw_jdk::install]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
      - recipe[fmw_inst::webcenter]
      - recipe[fmw_inst::soa_suite]
      - recipe[fmw_inst::service_bus]
    attributes:
      fmw:
        java_home_dir:           "/usr/jdk/instances/jdk1.7.0_75"
        middleware_home_dir:     "/opt/oracle/middleware_1036"
        version:                 "10.3.6"
      fmw_jdk:
        source_file:             "/software/jdk-7u75-solaris-i586.tar.gz"
        source_x64_file:         "/software/jdk-7u75-solaris-x64.tar.gz"
      fmw_wls:
        source_file:             "/software/wls1036_generic.jar"
      fmw_inst:
        soa_suite_source_file:   "/software/ofm_soa_generic_11.1.1.7.0_disk1_1of2.zip"
        soa_suite_source_2_file: "/software/ofm_soa_generic_11.1.1.7.0_disk1_2of2.zip"
        service_bus_source_file: "/software/ofm_osb_generic_11.1.1.7.0_disk1_1of1.zip"
        webcenter_source_file:   "/software/ofm_wc_generic_11.1.1.9.0_disk1_1of2.zip"
        webcenter_source_2_file: "/software/ofm_wc_generic_11.1.1.9.0_disk1_2of2.zip"
    excludes:
      - windows-2012r2
      - windows-8.1
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8

  - name: wls1036_win
    run_list:
      - recipe[artifact-deployer]
      - recipe[fmw_jdk::install]
      - recipe[fmw_wls::install]
      - recipe[fmw_inst::webcenter]
      - recipe[fmw_inst::soa_suite]
      - recipe[fmw_inst::service_bus]
    attributes:
      fmw:
        java_home_dir:           "C:/java/jdk1.7.0_75"
        middleware_home_dir:     "C:/oracle/middleware_1036"
        version:                 "10.3.6"
        tmp_dir:                 "C:\\Users\\vagrant\\AppData\\Local\\temp"
      fmw_jdk:
        source_file:             "C:/software/jdk-7u75-windows-x64.exe"
      fmw_wls:
        source_file:             "C:/software/wls1036_generic.jar"
      fmw_inst:
        soa_suite_source_file:   "C:/software/ofm_soa_generic_11.1.1.7.0_disk1_1of2.zip"
        soa_suite_source_2_file: "C:/software/ofm_soa_generic_11.1.1.7.0_disk1_2of2.zip"
        service_bus_source_file: "C:/software/ofm_osb_generic_11.1.1.7.0_disk1_1of1.zip"
        webcenter_source_file:   "C:/software/ofm_wc_generic_11.1.1.9.0_disk1_1of2.zip"
        webcenter_source_2_file: "C:/software/ofm_wc_generic_11.1.1.9.0_disk1_2of2.zip"
    excludes:
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8
      - solaris-11.2
      - solaris-10
